In [1]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load datasets
stints_2023 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2023/stints_clean.csv")
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/stints_2024.csv")

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Features and target
X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint"
    ]
]

y = model_df["StintLength"]

# Pipeline
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Evaluate
preds = model.predict(X_test)

mae = mean_absolute_error(
    y_test,
    preds
)

print("Combined Dataset MAE:", mae)
print("Total stints:", len(model_df))

Combined Dataset MAE: 6.282319064752515
Total stints: 2427

In [21]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# ==========================
# Load datasets
# ==========================

stints_2023 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2023/stints_clean.csv")
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/stints_2024.csv")


# Add season labels
stints_2023["Season"] = "2023"
stints_2024["Season"] = "2024"

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

print("Combined stints:", combined_stints.shape)

# ==========================
# Feature Engineering
# ==========================

model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"].astype(str)
    + "_S"
    + model_df["Stint"].astype(str)
)

# ==========================
# Features and Target
# ==========================

X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season"
    ]
]

y = model_df["StintLength"]

# ==========================
# Preprocessing
# ==========================

categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint",
    "Season"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

# ==========================
# Model
# ==========================

model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# ==========================
# Train/Test Split
# ==========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ==========================
# Training
# ==========================

model.fit(
    X_train,
    y_train
)

# ==========================
# Evaluation
# ==========================

preds = model.predict(X_test)

mae = mean_absolute_error(
    y_test,
    preds
)

print("\n===== Phase 2B.1 Results =====")
print(f"MAE with Season Feature: {mae:.4f}")
print("Previous MAE: 6.2823")
print(f"Delta: {mae - 6.2823:.4f}")

Combined stints: (2427, 6)

===== Phase 2B.1 Results =====
MAE with Season Feature: 6.2012
Previous MAE: 6.2823
Delta: -0.0811

#### Weather-Feature Testing

In [6]:
#2023 
import pandas as pd

merged_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/final_merged_2023_data.csv"
)

weather_stints_2023 = (
    merged_2023
    .groupby(
        ["GP", "Driver", "Stint"]
    )[
        ["AirTemp", "TrackTemp"]
    ]
    .mean()
    .reset_index()
)

print(weather_stints_2023.shape)
weather_stints_2023.head()

(2216, 5)

C:\Users\VANSH\AppData\Local\Temp\ipykernel_12672\1084341378.py:4: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_2023 = pd.read_csv(

                     GP Driver  Stint  AirTemp  TrackTemp
0  Abu Dhabi Grand Prix    ALB      1      NaN        NaN
1  Abu Dhabi Grand Prix    ALB      2      NaN        NaN
2  Abu Dhabi Grand Prix    ALB      3      NaN        NaN
3  Abu Dhabi Grand Prix    ALB      4      NaN        NaN
4  Abu Dhabi Grand Prix    ALB      5      NaN        NaN

In [8]:
#2024
merged_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/final_merged_2024_data.csv"
)

weather_stints_2024 = (
    merged_2024
    .groupby(
        ["GP", "Driver", "Stint"]
    )[
        ["AirTemp", "TrackTemp"]
    ]
    .mean()
    .reset_index()
)

print(weather_stints_2024.shape)
weather_stints_2024.head()

(2000, 5)

                     GP Driver  Stint    AirTemp  TrackTemp
0  Abu Dhabi Grand Prix    ALB      1  26.875000  31.766667
1  Abu Dhabi Grand Prix    ALB      2  26.288889  30.377778
2  Abu Dhabi Grand Prix    ALO      1  26.876923  31.723077
3  Abu Dhabi Grand Prix    ALO      2  26.504167  30.895833
4  Abu Dhabi Grand Prix    ALO      3  26.014286  29.704762

In [9]:
#weather_stint_dataset merge
stints_2023 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2023/stints_clean.csv")
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/stints_2024.csv")

stints_2023_weather = stints_2023.copy()
stints_2024_weather = stints_2024.copy()

stints_2023_weather.to_csv(
    "stints_2023_weather.csv",
    index=False
)

stints_2024_weather.to_csv(
    "stints_2024_weather.csv",
    index=False
)

In [14]:
#2023
stints_2023 = pd.read_csv("C:/Users/VANSH/Formula1/notebooks/stints_2023_weather.csv")

stints_2023_weather = stints_2023.merge(
    weather_stints_2023,
    on=["GP", "Driver", "Stint"],
    how="left"
)
print(stints_2023_weather.shape)
stints_2023_weather.head()
stints_2023_weather.to_csv(
    "stints_2023_weather.csv", index=False)

(1198, 7)

In [ ]:
#2024
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/notebooks/stints_2024_weather.csv")

stints_2024_weather = stints_2024.merge(
    weather_stints_2024,
    on=["GP", "Driver", "Stint"],
    how="left"
)
print(stints_2024_weather.shape)
stints_2024_weather.head()
stints_2024_weather.to_csv(
    "stints_2024_weather.csv", index=False)
print("Weather data merged and saved for both seasons.")

(1229, 7)
Weather data merged and saved for both seasons.

In [16]:
print(
    stints_2023_weather[
        ["AirTemp", "TrackTemp"]
    ]
    .isna()
    .sum()
)

print(
    stints_2024_weather[
        ["AirTemp", "TrackTemp"]
    ]
    .isna()
    .sum()
)

AirTemp      0
TrackTemp    0
dtype: int64
AirTemp      0
TrackTemp    0
dtype: int64

In [ ]:
stints_2023_weather["Season"] = "2023"
stints_2024_weather["Season"] = "2024"

combined_stints = pd.concat(
    [
        stints_2023_weather,
        stints_2024_weather
    ],
    ignore_index=True
)

In [12]:
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/stints_2024_weather.csv")
stints_2024["Compound"].value_counts()

Compound
HARD            511
MEDIUM          465
SOFT            141
INTERMEDIATE    105
WET               7
Name: count, dtype: int64

In [18]:
weather_df_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/cleaned_weather_2024.csv")
weather_df_2024.columns

Index(['Time', 'AirTemp', 'Humidity', 'Pressure', 'Rainfall', 'TrackTemp',
       'WindDirection', 'WindSpeed', 'RoundNumber', 'EventName', 'Session',
       'Date'],
      dtype='object')

In [19]:
weather_df_2023 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2023/weather_2023_cleaned.csv")
weather_df_2023.columns

Index(['Time', 'AirTemp', 'Humidity', 'Pressure', 'Rainfall', 'TrackTemp',
       'WindDirection', 'WindSpeed', 'RoundNumber', 'EventName', 'Session',
       'Date'],
      dtype='object')

In [20]:
print(weather_df_2023["Rainfall"].value_counts(dropna=False))
print(weather_df_2024["Rainfall"].value_counts(dropna=False))

Rainfall
False    9447
True      579
Name: count, dtype: int64
Rainfall
False    6936
True      481
Name: count, dtype: int64

In [26]:
stints_2023 = pd.read_csv("stints_2023_weather.csv")
stints_2024 = pd.read_csv("stints_2024_weather.csv")

combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

model_df = combined_stints.copy()
model_df.columns

Index(['GP', 'Driver', 'Stint', 'Compound', 'StintLength', 'AirTemp',
       'TrackTemp'],
      dtype='object')

In [1]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load weather-enhanced stint datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_2023_weather.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_2024_weather.csv"
)


stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Features and target
X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp",
        "TrackTemp"
    ]
]

y = model_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp",
    "TrackTemp"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Combined Dataset MAE with both TrackTemp and AirTemp: ", mae)
print("Total stints:", len(model_df))

Combined Dataset MAE with both TrackTemp and AirTemp:  6.143372292968852
Total stints: 2427

In [2]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load weather-enhanced stint datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_2023_weather.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_2024_weather.csv"
)
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Features and target
X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "TrackTemp"
    ]
]

y = model_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "TrackTemp"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Combined Dataset MAE with TrackTemp only: ", mae)
print("Total stints:", len(model_df))

Combined Dataset MAE with TrackTemp only:  6.172989315907902
Total stints: 2427

In [8]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load weather-enhanced stint datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_2023_weather.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_2024_weather.csv"
)
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Features and target
X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp"
    ]
]

y = model_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Combined Dataset MAE with AirTemp only: ", mae)
print("Total stints:", len(model_df))

Combined Dataset MAE with AirTemp only:  6.215521531462013
Total stints: 2427

#### To check rainy GPs in 2023 and 2024

In [3]:
import pandas as pd

weather_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/weather_2023_cleaned.csv"
)

weather_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/cleaned_weather_2024.csv"
)

combined_weather = pd.concat(
    [weather_2023, weather_2024],
    ignore_index=True
)

rain_summary = (
    combined_weather
    .groupby("EventName")["Rainfall"]
    .sum()
    .reset_index()
    .sort_values("Rainfall", ascending=False)
)

print(rain_summary)

                    EventName  Rainfall
7         Canadian Grand Prix       210
6          British Grand Prix       192
11       Hungarian Grand Prix       133
22       São Paulo Grand Prix       122
5          Belgian Grand Prix       100
9            Dutch Grand Prix        98
21         Spanish Grand Prix        75
1       Australian Grand Prix        47
17          Monaco Grand Prix        33
13        Japanese Grand Prix        26
15     Mexico City Grand Prix        18
2         Austrian Grand Prix         4
23   United States Grand Prix         2
20       Singapore Grand Prix         0
19   Saudi Arabian Grand Prix         0
18           Qatar Grand Prix         0
0        Abu Dhabi Grand Prix         0
16           Miami Grand Prix         0
14       Las Vegas Grand Prix         0
10  Emilia Romagna Grand Prix         0
8          Chinese Grand Prix         0
4          Bahrain Grand Prix         0
3       Azerbaijan Grand Prix         0
12         Italian Grand Prix         0

In [4]:
race_weather = (
    combined_weather
    .groupby("EventName")
    .agg(
        RainySamples=("Rainfall", "sum"),
        TotalSamples=("Rainfall", "count")
    )
)

race_weather["RainPct"] = (
    race_weather["RainySamples"]
    / race_weather["TotalSamples"]
    * 100
)

race_weather = race_weather.sort_values(
    "RainPct",
    ascending=False
)

print(
    race_weather[
        ["RainySamples", "TotalSamples", "RainPct"]
    ]
)

                           RainySamples  TotalSamples    RainPct
EventName
Canadian Grand Prix                 210           928  22.629310
São Paulo Grand Prix                122           550  22.181818
Belgian Grand Prix                  100           470  21.276596
British Grand Prix                  192           964  19.917012
Dutch Grand Prix                     98           706  13.881020
Hungarian Grand Prix                133          1057  12.582781
Spanish Grand Prix                   75           960   7.812500
Australian Grand Prix                47          1011   4.648863
Monaco Grand Prix                    33          1001   3.296703
Mexico City Grand Prix               18           670   2.686567
Japanese Grand Prix                  26           993   2.618328
Austrian Grand Prix                   4           620   0.645161
United States Grand Prix              2           484   0.413223
Singapore Grand Prix                  0           693   0.000000
Saudi Arabian Grand Prix              0           970   0.000000
Qatar Grand Prix                      0           475   0.000000
Abu Dhabi Grand Prix                  0           626   0.000000
Miami Grand Prix                      0           791   0.000000
Las Vegas Grand Prix                  0           582   0.000000
Emilia Romagna Grand Prix             0           453   0.000000
Chinese Grand Prix                    0           333   0.000000
Bahrain Grand Prix                    0           991   0.000000
Azerbaijan Grand Prix                 0           501   0.000000
Italian Grand Prix                    0           614   0.000000

In [5]:
race_weather = combined_weather[
    combined_weather["Session"] == "R"
].copy()

race_weather = (
    race_weather
    .groupby("EventName")
    .agg(
        RainySamples=("Rainfall", "sum"),
        TotalSamples=("Rainfall", "count")
    )
)

race_weather["RainPct"] = (
    race_weather["RainySamples"]
    / race_weather["TotalSamples"]
    * 100
)

race_weather = race_weather.sort_values(
    "RainPct",
    ascending=False
)

print(race_weather)

                           RainySamples  TotalSamples    RainPct
EventName
São Paulo Grand Prix                118           384  30.729167
British Grand Prix                   51           298  17.114094
Dutch Grand Prix                     48           362  13.259669
Canadian Grand Prix                  31           275  11.272727
Monaco Grand Prix                    26           376   6.914894
Belgian Grand Prix                   11           287   3.832753
Austrian Grand Prix                   4           296   1.351351
Spanish Grand Prix                    1           308   0.324675
Abu Dhabi Grand Prix                  0           304   0.000000
Mexico City Grand Prix                0           349   0.000000
Singapore Grand Prix                  0           336   0.000000
Saudi Arabian Grand Prix              0           294   0.000000
Qatar Grand Prix                      0           310   0.000000
Miami Grand Prix                      0           305   0.000000
Italian Grand Prix                    0           289   0.000000
Las Vegas Grand Prix                  0           251   0.000000
Japanese Grand Prix                   0           339   0.000000
Australian Grand Prix                 0           366   0.000000
Hungarian Grand Prix                  0           319   0.000000
Emilia Romagna Grand Prix             0           143   0.000000
Chinese Grand Prix                    0           165   0.000000
Bahrain Grand Prix                    0           318   0.000000
Azerbaijan Grand Prix                 0           312   0.000000
United States Grand Prix              0           323   0.000000

#### Dry Races MAE

In [6]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load weather-enhanced stint datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_weather_2023.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_weather_2024.csv"
)

# Add season feature
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Wet races identified from Race-session RainPct > 5%
wet_races = [
    "São Paulo Grand Prix",
    "British Grand Prix",
    "Dutch Grand Prix",
    "Canadian Grand Prix",
    "Monaco Grand Prix"
]

# Create dry-only dataset
dry_df = model_df[
    ~model_df["GP"].isin(wet_races)
].copy()

print("Original stints:", len(model_df))
print("Dry-only stints:", len(dry_df))

# Features and target
X = dry_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp",
        "TrackTemp"
    ]
]

y = dry_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp",
    "TrackTemp"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Dry-Only Dataset MAE:", mae)

Original stints: 2427
Dry-only stints: 1872
Dry-Only Dataset MAE: 5.829821737045296

#### Merging weather stint & freshtyre stint

In [ ]:
#2023
import pandas as pd

weather_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_weather_2023.csv"
)

fresh_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_freshtyre_2023.csv"
)

stints_master_2023 = weather_2023.merge(
    fresh_2023[
        [
            "GP",
            "Driver",
            "Stint",
            "Compound",
            "FreshTyre"
        ]
    ],
    on=[
        "GP",
        "Driver",
        "Stint",
        "Compound"
    ],
    how="left"
)

print(stints_master_2023.shape)
print(stints_master_2023.isna().sum())

stints_master_2023.to_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv",
    index=False
)

(1198, 8)
GP             0
Driver         0
Stint          0
Compound       0
StintLength    0
AirTemp        0
TrackTemp      0
FreshTyre      0
dtype: int64

In [3]:
#2024
import pandas as pd

weather_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_weather_2024.csv"
)

fresh_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_freshtyre_2024.csv"
)

stints_master_2024 = weather_2024.merge(
    fresh_2024[
        [
            "GP",
            "Driver",
            "Stint",
            "Compound",
            "FreshTyre"
        ]
    ],
    on=[
        "GP",
        "Driver",
        "Stint",
        "Compound"
    ],
    how="left"
)

print(stints_master_2024.shape)
print(stints_master_2024.isna().sum())

stints_master_2024.to_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv",
    index=False
)

(1229, 8)
GP             0
Driver         0
Stint          0
Compound       0
StintLength    0
AirTemp        0
TrackTemp      0
FreshTyre      0
dtype: int64

In [4]:
print(stints_master_2023.columns.tolist())
print(stints_master_2024.columns.tolist())

['GP', 'Driver', 'Stint', 'Compound', 'StintLength', 'AirTemp', 'TrackTemp', 'FreshTyre']
['GP', 'Driver', 'Stint', 'Compound', 'StintLength', 'AirTemp', 'TrackTemp', 'FreshTyre']

In [5]:
print(stints_master_2023["FreshTyre"].isna().sum())
print(stints_master_2024["FreshTyre"].isna().sum())

0
0

In [1]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load master datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv"
)

# Add season feature
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Dry-only benchmark
wet_races = [
    "São Paulo Grand Prix",
    "British Grand Prix",
    "Dutch Grand Prix",
    "Canadian Grand Prix",
    "Monaco Grand Prix"
]

dry_df = model_df[
    ~model_df["GP"].isin(wet_races)
].copy()

print("Original stints:", len(model_df))
print("Dry-only stints:", len(dry_df))

# Features
X = dry_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp",
        "TrackTemp",
        "FreshTyre"
    ]
]

y = dry_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp",
    "TrackTemp",
    "FreshTyre"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Dry-Only + FreshTyre MAE:", mae)
print("Total stints:", len(dry_df))

Original stints: 2427
Dry-only stints: 1872
Dry-Only + FreshTyre MAE: 5.837993781054278
Total stints: 1872

#### Race_progress Feature addition (2023)

In [3]:
import pandas as pd

# Load lap-level dataset
laps_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/final_merged_2023_data.csv"
)

# Race laps only
race_laps_2023 = laps_2023[
    laps_2023["Session"] == "R"
].copy()

# Stint start lap
stint_start_2023 = (
    race_laps_2023
    .groupby(
        ["GP", "Driver", "Stint", "Compound"],
        as_index=False
    )
    .agg(
        StintStartLap=("LapNumber", "min")
    )
)

# Total race laps per GP
race_laps_total_2023 = (
    race_laps_2023
    .groupby("GP", as_index=False)
    .agg(
        TotalRaceLaps=("LapNumber", "max")
    )
)

# Merge and calculate RaceProgress
race_progress_2023 = stint_start_2023.merge(
    race_laps_total_2023,
    on="GP",
    how="left"
)

race_progress_2023["RaceProgress"] = (
    race_progress_2023["StintStartLap"]
    / race_progress_2023["TotalRaceLaps"]
)

# Load master dataset
master_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv"
)

# Merge RaceProgress
master_2023 = master_2023.merge(
    race_progress_2023[
        [
            "GP",
            "Driver",
            "Stint",
            "Compound",
            "RaceProgress"
        ]
    ],
    on=[
        "GP",
        "Driver",
        "Stint",
        "Compound"
    ],
    how="left"
)

print(master_2023.shape)
print(master_2023["RaceProgress"].isna().sum())

master_2023.to_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv",
    index=False
)

C:\Users\VANSH\AppData\Local\Temp\ipykernel_22320\138132886.py:4: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  laps_2023 = pd.read_csv(

(1198, 9)
0

In [7]:
master_2023['RaceProgress'].head(10)

0    0.018519
1    0.018519
2    0.185185
3    0.018519
4    0.037037
5    0.185185
6    0.018519
7    0.185185
8    0.851852
9    0.018519
Name: RaceProgress, dtype: float64

#### Race_progress addition 2024

In [10]:
import pandas as pd

# Load lap-level dataset
laps_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/final_merged_2024_data.csv"
)

# Race laps only
race_laps_2024 = laps_2024[
    laps_2024["SessionType"] == "R"
].copy()

# Stint start lap
stint_start_2024 = (
    race_laps_2024
    .groupby(
        ["GP", "Driver", "Stint", "Compound"],
        as_index=False
    )
    .agg(
        StintStartLap=("LapNumber", "min")
    )
)

# Total race laps per GP
race_laps_total_2024 = (
    race_laps_2024
    .groupby("GP", as_index=False)
    .agg(
        TotalRaceLaps=("LapNumber", "max")
    )
)

# Merge and calculate RaceProgress
race_progress_2024 = stint_start_2024.merge(
    race_laps_total_2024,
    on="GP",
    how="left"
)

race_progress_2024["RaceProgress"] = (
    race_progress_2024["StintStartLap"]
    / race_progress_2024["TotalRaceLaps"]
)

# Load master dataset
master_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv"
)

# Merge RaceProgress
master_2024 = master_2024.merge(
    race_progress_2024[
        [
            "GP",
            "Driver",
            "Stint",
            "Compound",
            "RaceProgress"
        ]
    ],
    on=[
        "GP",
        "Driver",
        "Stint",
        "Compound"
    ],
    how="left"
)

print(master_2024.shape)
print(master_2024["RaceProgress"].isna().sum())

master_2024.to_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv",
    index=False
)

(1229, 9)
0

In [11]:
master_2024.head(10)

,GP,Driver,Stint,Compound,StintLength,AirTemp,TrackTemp,FreshTyre,RaceProgress
0,Abu Dhabi Grand Prix,ALB,1,MEDIUM,12,26.875000,31.766667,1,0.017241
1,Abu Dhabi Grand Prix,ALB,2,HARD,45,26.288889,30.377778,1,0.224138
2,Abu Dhabi Grand Prix,ALO,1,MEDIUM,14,26.876923,31.723077,0,0.017241
3,Abu Dhabi Grand Prix,ALO,2,HARD,25,26.504167,30.895833,0,0.241379
4,Abu Dhabi Grand Prix,ALO,3,HARD,22,26.014286,29.704762,0,0.655172
5,Abu Dhabi Grand Prix,BOT,1,MEDIUM,6,26.900000,31.883333,1,0.017241
6,Abu Dhabi Grand Prix,BOT,2,HARD,23,26.652174,31.230435,1,0.120690
7,Abu Dhabi Grand Prix,COL,1,MEDIUM,3,26.933333,31.933333,1,0.017241
8,Abu Dhabi Grand Prix,COL,2,HARD,23,26.713043,31.321739,1,0.068966
9,Abu Dhabi Grand Prix,DOO,1,MEDIUM,22,26.790909,31.550000,1,0.017241

In [2]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load master datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv"
)

# Add season feature
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Dry-only benchmark
wet_races = [
    "São Paulo Grand Prix",
    "British Grand Prix",
    "Dutch Grand Prix",
    "Canadian Grand Prix",
    "Monaco Grand Prix"
]

dry_df = model_df[
    ~model_df["GP"].isin(wet_races)
].copy()

print("Original stints:", len(model_df))
print("Dry-only stints:", len(dry_df))

# Features
X = dry_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp",
        "TrackTemp",
        #"FreshTyre",
        "RaceProgress"
    ]
]

y = dry_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp",
    "TrackTemp",
    #"FreshTyre",
    "RaceProgress"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Dry-Only + FreshTyre + RaceProgress MAE:", mae)
print("Total stints:", len(dry_df))

Original stints: 2427
Dry-only stints: 1872
Dry-Only + FreshTyre + RaceProgress MAE: 5.676825382307484
Total stints: 1872

In [ ]:
%pip install xgboost
import xgboost as xgb